### ISSUE TITLE
Combine Initiative & Pass Arrow

### ISSUE THREAD

**Issue by vjjft** [tjjfvi/epiepic-paper#31]

**Comment by vjjft** [comment]
![image](https://user-images.githubusercontent.com/18031950/57171436-65d4eb80-6de2-11e9-949a-26ee62c7dd7e.png)

only active initiative would be shown; self ~blue, opp ~gray
only self waiting would pulse; self ~yellow, opp ~white

**Comment by tjjfvi** [comment]
And right arrow, right?

**Comment by vjjft** [comment]
Patch:
[side-style.zip](https://github.com/tjjfvi/epiepic-paper/files/3143972/side-style.zip)

@tjjfvi
