### ISSUE TITLE
Move Gold to Indicator Area

### ISSUE THREAD

**Issue by vjjft** [tjjfvi/epiepic-paper#8]

**Comment by tjjfvi** [comment]
Why?

**Comment by vjjft** [comment]
It is a major game state, often more important as to what one is doing than everything else, including turn & phase, but is currently down in a corner.

*(Relatedly: Digital recently added a 'Gold unplayed' indicator near the phase info, and it was one of the biggest usability improvements to date.)*

**Comment by tjjfvi** [comment]
Suggestion:
![](https://user-images.githubusercontent.com/44031566/57530586-95fe1c00-7305-11e9-908f-46ef68e79035.png)
